### ISSUE TITLE
GenericRenderWindow does not call setContainer on init

### ISSUE THREAD

**Issue by swederik** [Kitware/vtk-js#1014]
Hello!

The issue we are having is that GenericRenderWindow doesn't seem to act like FullScreenRenderWindow. It always seems to need to be resized first or interacted with before the data appears. It looks like it might be because it does not call setContainer on initialization.

https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/GenericRenderWindow/index.js
https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/FullScreenRenderWindow/index.js#L67

We've worked around this by adding some `.resize()` calls when creating everything. It is a bit weird though so I will probably fix it and send a PR soon.

**Comment by jourdain** [comment]
Yes that's expected. The generic one offload to the user to set the container (no default as it is not suppose to be full screen) and once you set the container or when you affect it's size (since you are in control), you have to call resize(). The full screen one take those requirement off to the user has when you are fullscreen you can easily create a container for it that will spread to the window size and bind the resize on the window size change event.

If your container is a fixed size, affecting the window size, won't affect that container size therefore we do not make that binding automatically.
