### ISSUE TITLE
ZipMultiDataSetReader Unfinished

### ISSUE THREAD

**Issue by llangholz89** [Kitware/vtk-js#1194]
Am I losing it, or is the ZipMultiDataSetReader unfinished? It looks like there was a [note](https://github.com/Kitware/vtk-js/blob/master/Sources/IO/Core/ZipMultiDataSetReader/index.js#L86) to perform the deserialization of the fetched zipped datasets and assign them to the algo's output, but it was never implemented.  Is this still a WIP??

**Comment by jourdain** [comment]
It seems like it. The writer seems to be fully completed but the reader indeed seems to be missing some of it.

**Comment by llangholz89** [comment]
Got it. That was more a sanity check on my end than a request to complete it ;)

**Comment by jourdain** [comment]
This kind of things unfortunately happen when I code during travel and then I have no time to complete it. I guess it went in when we got the svg overlay that @floryst finished for me as it was required for one of our project. I'll try to finish it since not much is missing... ;-) 

Thanks for bringing it to our attention.

**Comment by jourdain** [comment]
Closing for now
