### ISSUE TITLE
Transferring rendered content from vtk into an separate/external rendering context

### ISSUE THREAD

**Issue by gavargas22** [Kitware/vtk-js#1260]
I am figuring out the inner workings of WebGL and vtk.js in general so apologies if the question is unclear...

I have a webgl context that runs on a browser application. I would like to use the volume renderer features of vtk.js to display a volume on that webgl context.

Is there a way to override the webgl context used by vtk.js?

Has anyone attempted this or have any ideas on how to accomplish this?

**Comment by floryst** [comment]
Currently, vtk.js controls the canvas/webgl context it creates. You can technically override the canvas element via `openglRenderWindow.set({ canvas: otherCanvas })`, but such an action is not supported.

What is your use-case? Are you trying to render a volume into an existing scene that's controlled by some other library/code? If so, I don't think that's supported due to two libraries trying to draw their own stuff to the same context. If you're trying to just do a volume rendering, then you should use `openglRenderWindow.setContainer(element)` ([ref](https://kitware.github.io/vtk-js/examples/VolumeMapper.html)) and let vtk.js control creation of the canvas/webgl context.

**Comment by gavargas22** [comment]
So I am attempting to render a volume from vtkjs into another existing scene. 

The existing scene does allow and is set up for external renderers to generate a webgl visualization for example with ThreeJS and then drop in the result in the original webgl context. Example: [https://developers.arcgis.com/javascript/latest/sample-code/scene-external-renderer-threejs/index.html](https://developers.arcgis.com/javascript/latest/sample-code/scene-external-renderer-threejs/index.html)

I am trying to use vtk to generate a rendering of a volume (taking the place of threejs), which then can be sent to that other webgl context.

**Comment by floryst** [comment]
Ah, so vtk.js currently does not support using an external webgl context, since it depends on a canvas for listening for interactions, size information, and possibly other info.

That being said, there might be some hackery that can be done to try to support this use-case. I don't have any specifics, but check out `Sources/Rendering/OpenGL/RenderWindow/index.js`, which is our entry point for setting up our webgl context and canvas. Just don't expect any sort of vtk.js interaction to work, of course.

@martinken this might be an interesting use-case to consider.

**Comment by gavargas22** [comment]
Thank you for your input @floryst !

Let me know if you have any ideas @martinken
