### ISSUE TITLE
Getting the interactor that set a manipulator from inside the manipulator?

### ISSUE THREAD

**Issue by mix3d** [Kitware/vtk-js#1268]
I have a custom Interactor class (extending from `vtkInteractorStyleManipulator`), that conditionally sets various mouse manipulator classes (similar to the [InteractorStyleManipulator example](https://kitware.github.io/vtk-js/examples/InteractorStyleManipulator.html)), but the values passed into the manipulator for the `interactor` parameter of the onMouse functions is not the interactor that is setting them via `addMouseManipulator()`, instead it is of class `vtkRenderWindowInteractor`

Why doesn't the manipulator have access to the interactor that created/setup said manipulator?

**Comment by floryst** [comment]
Do you mean letting manipulators access your custom InteractorStyle class? To help clear up any confusion, `vtkInteractorStyleManipulator` is an InteractorStyle, not an Interactor.

The `interactor` parameter of the onMouse functions is correct: it should be a `vtkRenderWindowInteractor`. Currently, Manipulators do not know about the `vtkInteractorStyleManipulator` object that uses them. However, since you have a custom InteractorStyle class (and likely custom Manipulators), then you can pass in your custom InteractorStyle object into the constructor of your Manipulators.

**Comment by mix3d** [comment]
I'll chalk that up to still not really understanding the object hierarchy of VTK yet. 

Yes, I can make all my manipulators have a constructor option that includes the root interactorManipulator, but I hoped it would be cleaner than that. 

Oh well!
