### ISSUE TITLE
Mapper image interpolation

### ISSUE THREAD

**Issue by juanprietob** [Kitware/vtk-js#1293]
There seems to be an interpolation done in the image which reduces the resolution. The lower resolution image is then given to the HTML5 canvas? 

Repository with vtk.js code https://github.com/juanprietob/react-med-img-viewer.git

@floryst 

![image](https://user-images.githubusercontent.com/7086191/70928473-21a7fb80-1fff-11ea-8f60-7b3621727172.png)

**Comment by floryst** [comment]
The issue is that the canvas is still 300x300. This means the whole scene is rendered into 300x300, and then the resulting canvas is upscaled to the containing container, causing the image to look resampled.

In your `MedImgView` class, you should have some logic to set the `openglRenderWindow` size to the size of the containing window. You can see an example of this here: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/FullScreenRenderWindow/index.js#L145

Let me know if that works for you.

**Comment by juanprietob** [comment]
Yes, that works!
The canvas needs to be resized according to the container!
