### ISSUE TITLE
How do I add a controller to a vtkRenderWindow ?

### ISSUE THREAD

**Issue by EmmanuelMadarassou** [Kitware/vtk-js#1489]
Hi everyone, the title is pretty explicit. I try to add a controller to my view which is inside a html container div. Can anyone light me ?

Here is my code: 

this.renderWindow = vtkRenderWindow.newInstance();
this.renderer = vtkRenderer.newInstance({ background: [0.2, 0.3, 0.4] });
this.renderWindow.addRenderer(this.renderer);

this.openglRenderWindow = vtkOpenGLRenderWindow.newInstance();
this.renderWindow.addView(this.openglRenderWindow);

this.openglRenderWindow.setContainer(container);

const { width, height } = container.getBoundingClientRect();
this.openglRenderWindow.setSize(width, height);

**Comment by jourdain** [comment]
```
const controller = document.createElement('div');
container.appendChild(controller);
```

**Comment by Timanu05** [comment]
So I assume there's not any method to manipulate controller like in the vtkFullScreenRenderWindow, right ?

**Comment by jourdain** [comment]
vtkFullScreenRenderWindow provide [helper to add a div](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Misc/FullScreenRenderWindow/index.js#L104-L120) in a specific location for you to create some controller panel.

But in general vtkFullScreenRenderWindow is really good for small and easy examples. For a real application, you should take over the handling of the HTML while letting vtk.js put its content in a DOM element that you control rather than a fullscreen mode.
