### ISSUE TITLE
Boolean operations on vtkPolyData

### ISSUE THREAD

**Issue by a3VonG** [Kitware/vtk-js#1507]
Hi everyone! 

I would like to perform operations such as UNION, INTERSECTION, DIFFERENCE between vtkPolyData coming from different .stl's. 
The filter that I think that the filter that might do the job is the ["vtkBooleanOperationPolyDataFilter"](https://vtk.org/doc/nightly/html/classvtkBooleanOperationPolyDataFilter.html) , which is present in VTK but not (yet) in vtk.js.  

Is it possible to achieve this result by using already present filters in vtk.js? 
If not,  is this planned in future releases? 
What would be the steps needed to start implementing this? 

Thank you!

**Comment by jourdain** [comment]
I glance through the code of the vtkBooleanOperationPolyDataFilter and it looks like that it would be easier to rely on a web-assembly version of that code rather than implementing it in JS as it brings a lot of dependencies (octree, cells, delaunay, ...) into the mix. 

So to do it, I would create a C++ version of the app and drive it from the web like the examples you can find [here](https://github.com/Kitware/VTK/tree/master/Examples/Emscripten/Cxx).

HTH

**Comment by a3VonG** [comment]
Thank you for your reply! 
I can see now that this would indeed introduce a lot of dependencies.  However, the functionality would need to be integrated inside of an existing project which uses vtk.js. 
Do you think it is possible to use C++ driven from the web just for the needed filter, without creating a C++ version of the full app?

**Comment by jourdain** [comment]
What I mean is to create a WebAssembly package of some C++ part of VTK that will run inside your browser. You could either do rendering via webassembly or just data processing while keeping the rendering inside vtk.js.

**Comment by a3VonG** [comment]
Awesome thank you for your help, I'll try that approach  👍
