### ISSUE TITLE
Create a slab via ImageReslice

### ISSUE THREAD

**Issue by pvrobays** [Kitware/vtk-js#1566]
Hi

Is it possible to create a slab of a certain thickness via the `ImageReslice`?
I know VTK has an `ImageSlabReslice`, but this doesn't seem to exist in Vtk.js.

I did spot a `slabMode` and `slabNumberOfSlices` property in `ImageReslice`, but I'm unable to find any setters?

**Comment by floryst** [comment]
@finetjul @laurennlam

**Comment by finetjul** [comment]
I do not remember implementing it because I did not need it at that time. See [getCompositeFunc](https://github.com/Kitware/vtk-js/blob/master/Sources/Imaging/Core/ImageReslice/index.js#L829) 

Feel free to add the missing function by taking a look at the [C++ implementation](https://github.com/Kitware/VTK/blob/master/Imaging/Core/vtkImageReslice.cxx#L1555)

That can be a useful feature to add. Thanks.

**Comment by daker** [comment]
@finetjul Implemented in #1727 maybe close this one?

**Comment by finetjul** [comment]
@gandis0713  did the implementation, not me.

Closing the issue.
