### ISSUE TITLE
Can VTK.js  slice  on the polydata?

### ISSUE THREAD

**Issue by rookieforever** [Kitware/vtk-js#1640]
Hi,I'm a beginner to vtk.js and I've ever used paraview for visualizing my data.
It seems paraview can do slice to my VTP file or STL file,yet it does not  work on vtk.js project.The usual movement like slice、clip only work for image file like vti.I've tried the examples like ImageCropFilter ,but won't work and I get a error report :"get.extent() is not a function."The only api works for me is cutter,which is a line and won't provide the inner structure of model.
I have seen the issue which is simliar to mine. https://github.com/Kitware/vtk-js/issues/1045 
I'm still kinda confused and can someone tell me that  can vtk.js slice on the data file except vti?

**Comment by jourdain** [comment]
Yes vtk.js can slice a vtkImageData(vti) and a vtkPolyData(obj, stl, vtp) but not an vtkUnstructuredGrid (vtu) or anything else.

Slicing is the action to cut (in this case via a plane) a given mesh and only keep the intersection. 
A polydata is a surface mesh, meaning that it is composed of triangles (2D), lines (1D), points (0D) cells. Therefore, when you cut any of those cells, you reduce by 1 their dimension. For example, when you intersect a triangle with a plane, you can only get a line which is exactly what you get with the cutter example. 

In order to have the inner structure of a model, you need 3D cells (tetrahedra or else) which don't exist in obj, stl types of mesh. But if you want to have your cutting plane filled when that part is inside the mesh, you need a more advanced cutter that will automatically fill the inside of the mesh that does not exist.

Or if you want to keep one side of the plane and don't really care about the closing cutting plane, then you are looking at a Clip filter. And I don't think we have one in vtk.js but it would be very close to what the cutter filter is doing while keeping one side of the mesh.

**Comment by rookieforever** [comment]
Thanks for your detailed and promptly response,jourdain.Think I kinda get it now.
