### ISSUE TITLE
where is PaintFilterWorker defined 

### ISSUE THREAD

**Issue by gzt036** [Kitware/vtk-js#1740]
PaintFilterWorker is missing and I cannot find it anywhere in the source directory. I got the error when using vtk.js

Attempted import error: 'vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker' does not contain a default export (imported as 'PaintFilterWorker').

**Comment by gzt036** [comment]
please check files 
vtk.js/Sources/Filters/General/PaintFilter/index.js 
vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker
in index.js, it imports
"import PaintFilterWorker from 'vtk.js/Sources/Filters/General/PaintFilter/PaintFilter.worker';"
, but nowhere in PaintFilter.worker.js is PaintFilterWorker defined, could someone please explain to me how this is supposed to work?

**Comment by floryst** [comment]
Hi, if you are using webpack then you'll need to include the vtk.js webpack rules. See: <https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html#Webpack-config>

If you are not using webpack, you can also try the beta version, installable at vtk.js@beta. you won't need build rules, and the only change is that vtk.js imports do not need the "Sources" directory in the path. (The docs are WIP so I can't link anything yet, and if you do try it with webpack 4, it doesnt quite work yet due to the exports field.)

**Comment by floryst** [comment]
If this is still an issue for you, please re-open.
