### ISSUE TITLE
vtkSphereMapper acting as mapper

### ISSUE THREAD

**Issue by zbouslikhin** [Kitware/vtk-js#1923]
### High-level description
Hello,

Trying the example of the [vtkSphereMapper with labels](https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html). 
It appears that the sphereMapper acts as a normal mapper as instead of sphere, a cone is rendered,

### Steps to reproduce
```js
    const coneSource = vtkConeSource.newInstance({ height: 1.0 });
    const meshActor = vtkActor.newInstance()
    const meshMapper = vtkSphereMapper.newInstance();
    meshMapper.setInputConnection(coneSource.getOutputPort());
    meshActor .setMapper(meshMapper);
```

### Detailed behavior
![image](https://user-images.githubusercontent.com/47977073/118543612-c8447e80-b754-11eb-8083-994a5d732416.png)

### Expected behavior
7 spheres that define the cone.

### Environment
- **vtk.js**: 18.1.1
- **OS**: Windows 10
- **Browser**: Chromium 83.0.4103.122 (Electron v9.4.1)

**Comment by zbouslikhin** [comment]
EDIT: after checking, such behavior appeared and is happening since v18.0.0.

**Comment by jourdain** [comment]
You need to load the [Molecule](https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Profiles/Molecule.js) profile in order to enable such mapper. This is a new behavior with 18. We let the user pick which piece of the rendering he is interested in so we can reduce the bundle size due to tree shaking.
