### ISSUE TITLE
npm install vtk-js doesnt work

### ISSUE THREAD

**Issue by arnoldmq** [Kitware/vtk-js#2]
I tried install vtk-js, vtk.js (which documentation says ) but neither is found.
from https://kitware.github.io/vtk-js it says to install using 
npm install vtk.js
but that package does not exist.

**Comment by jourdain** [comment]
Sorry but we haven't released vtk.js yet. That's why it is not yet available on npm. The documentation is a bit ahead of what is available today. Although, you can refer to vtk.js as a npm dependency like "Kitware/vtk-js" which will pull master from the git repo on github if you want to try before the release.
