### ISSUE TITLE
vtkPolyDataNormals - Cell Normals

### ISSUE THREAD

**Issue by emil-peters** [Kitware/vtk-js#2434]
### Need
At the moment, the `vtkPolyDataNormals` is only able to calculate the vertex normals.
I might be interesting to also compute the cell normals instead based on a programmatically set boolean.

Based on the suggestion of @finetjul in [this reply](https://discourse.vtk.org/t/polydata-normals/8550/2?u=emil-peter)

ps. You can assign me on this issue.

**Comment by luistorrescisneros** [comment]
I will use this spot to draw my concern cause it is somehow related. How it is posible to a attach a normal vector to a single point? I came across it, when using vtkPolyDataNormals to compute the normals of a cell, since a cell in some situations represents a surface. Basic mathematics teach us a normal vector can be computed solely on N-Dimensional (where N>2) surfaces!

**Comment by finetjul** [comment]
A point typically has the same normal of the cell.
I agree it is usually more useful to have cell normals than point normals.
