### ISSUE TITLE
ShapeWidget demo bug

### ISSUE THREAD

**Issue by haoxl3** [Kitware/vtk-js#2539]
### High-level description
bug 1. Error when drawing rectangleWidget in this [demo](https://kitware.github.io/vtk-js/examples/ShapeWidget.html). 
bug 2. Cannot draw more than one widget.

### Steps to reproduce
bug1: Select a rectangleWidget and release the mouse when you are finished, however the rectangleWidget doesn't show up on the image and disappears.
bug2: Select an ellipseWidget, after drawing can not continue to draw ellipseWidget, select other widgets after drawing, and then select ellipseWidget, the first time the ellipseWidget disappeared.

### Expected behavior
bug1: Expect to draw rectangleWidget normally.
bug2: Expect to be able to draw multiple widgets in a row.

### Environment
- **vtk.js**: 25.2.3
- **OS**:  10.14.6
- **Browser**: Chrome 103.0.5060.114

**Comment by floryst** [comment]
FYI @finetjul

**Comment by tomsuchel** [comment]
I may be answering too late but, as far I as know, this is the expected behavior for this example:

- The RectangleWidget is instantiated with the property `resetAfterPointPlacement` set to `true`, causing it to disappear when the mouse is released. 

- The three widgets (rectangle, elipse and circle) are only instantiated once, and are reset/grabbed (`scene.widgetManager.grabFocus(widgets[ev.target.value]);`) when switching between them. If you want to place multiple widgets, you can look at the [LabelWidget](https://kitware.github.io/vtk-js/examples/LabelWidget.html) or [LineWidget](https://kitware.github.io/vtk-js/examples/LineWidget.html) examples.
