### ISSUE TITLE
[Bug] Rendering issue when using ItkWasmGeometry

### ISSUE THREAD

**Issue by daker** [Kitware/vtk-js#2853]
### Bug description

| OBJReader |  ItkWasmGeometry |
:-------------------------:|:-------------------------:
| ![image](https://github.com/Kitware/vtk-js/assets/878518/c16e1322-79f9-4e97-88c1-58a0ed88867e) | ![image](https://github.com/Kitware/vtk-js/assets/878518/92b2d0dc-b8a1-43ae-9ddf-4b05891b3d2f)|

### Steps to reproduce

- Open https://kitware.github.io/vtk-js/examples/ItkWasmGeometry.html
- See the rendering

### Detailed Behavior

See bug description

### Expected Behavior

Same rendering of the same mesh

### Environment

- vtk.js version: 28.2.5
- Browsers: Chrome 114.0.5735.134
- OS: Windows 10

**Comment by Julesdevops** [comment]
I'll take a look

**Comment by Julesdevops** [comment]
This example uses an old release of itk-wasm. (1.0.0-b.8) Is this example still relevant? Is the `readMesh`/`meshToPolyData` still a thing in latest itk-wasm? @thewtex

**Comment by thewtex** [comment]
@Julesdevops thanks for taking a look.

Nothing has changed in itk-wasm related to this as far as I am aware.

The itk-wasm version could be bumped to the latest. Eventually the mesh reading and meshToPolyData functionaliyt will be separated into their own packages, but this has not happened, yet.

**Comment by Julesdevops** [comment]
Thanks for the info @thewtex 
The current situation can be reproduced up to itk-wasm@1.0.0-b.70. higher version up to itk-wasm@1.0.0-b.148 yield an internal error.  
Higher version (>= itk-wasm@1.0.0-b.148), I get CORS errors (cannot instantiate web worker scripts). Seems like it stops using a blob to load the web worker.  
I can take a deeper look at all of this in the next few days.

**Comment by thewtex** [comment]
@Julesdevops thanks for the investigation :clap: 

We could bump the version here to `itk-wasm@1.0.0-b.70`. Regarding the other issues, they will be resolved [when the mesh io is ported to its own package](https://github.com/InsightSoftwareConsortium/itk-wasm/issues/716) similar to the [@itk-wasm/image-io package](https://github.com/InsightSoftwareConsortium/itk-wasm/tree/main/packages/image-io/typescript), which provides its own [ESM bundle with an embedded web worker](https://www.jsdelivr.com/package/npm/@itk-wasm/image-io?tab=files&path=dist%2Fbundle).

But the issue we are seeing here was caused by something that changed in vtk.js. A good next step is to [`git bisect`](https://git-scm.com/docs/git-bisect) vtk.js on this example to find the commit that broke the rendering.

**Comment by Julesdevops** [comment]
Make sense. Took a look and another problem is that `itkWasmMeshToMeshFilter` [does not support int64 ](https://github.com/InsightSoftwareConsortium/itk-wasm/blob/main/include/itkWasmMeshToMeshFilter.hxx#L474)`cellComponentType`. Is it a desirable behavior?  
If not, we could fix it and bump to itk-wasm@1.0.0-b.147 probably.  
Though I also agree the root cause if in vtk.js, I'll look into it too

**Comment by Julesdevops** [comment]
First bad commit: cb3f7c13a48a877ef39cd56521fea0528b983

**Comment by Julesdevops** [comment]
Ok indeed it it logical not to support `int64` cellComponentType, my bad. Problem might be that we use`BitInt64Array`, where we should probably use `BigUInt64Array`, but thats out of the scope of this issue
