### ISSUE TITLE
How to use slicing with a loaded scene?

### ISSUE THREAD

**Issue by rmilne** [Kitware/vtk-js#379]
I'm trying to take a vtu file and display moveable slices in a browser window, similar to this example [MultiSliceImageMapper](https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html).

Should I be converting my vtu file to a vti format like the MultiSliceImageMapper example? 
I'm looking for some guidance but haven't found a more appropriate forum/list/chat channel.
(I apologize I am new to Paraview/VTK)

I'm certainly trying the wrong approach, but so far I have created two slice views in Paraview and exported the scene to a vtkjs zipped format using the python export script.  I can load it and it appears properly.  But attempting to move the slice by changing the sceneItem's position ( setPosition([x,y,z]) ) does not properly re-render the slice.  Here is the first scene followed by the attempt to move the slice.

![image](https://user-images.githubusercontent.com/863042/31910836-5d78765e-b804-11e7-9646-aeef4d6aaf1e.png)

![image](https://user-images.githubusercontent.com/863042/31911013-e9643fe0-b804-11e7-96b9-e49ec7ad9e65.png)

As a second attempt I've tried to add the vtkImageSlicer / mapper for one axis but it fails on rendering because there is no point data returned ( image.getPointData().getScalars().getMTime() ) so the getMTime() call fails to work on a null value.

Thanks for any help,
-Russ

**Comment by jourdain** [comment]
Hi Russ,

vtk.js does not support all the data structures than VTK itself support. For instance, vtk.js has been focusing on the rendering side and let the processing side a little bit aside for now.

By that, I mean, we don't really support volumetric cells unless they are part of an ImageData on which we'll use volume rendering for its rendering aspect.

In your use case when you export the geometry inside ParaView we actually extract the skin of that geometry so it can easily be rendered in OpenGL / WebGL. At that point we are missing the knowledge of the inside of the geometry. If we were slicing that geometry, you will only see lines instead of planes.

When you are moving those actors arounds you are just offsetting those geometry around without any recomputation. 

So what you are looking to achieve should be available in vtk.js at some point but probably not as soon as you would hope so.

The VolumeRendering / ImageData approach will work but might be overkill as you will have to over sample your dataset in order to get something reasonable. 

Another option would be to precompute each slice position inside ParaView and render them independently inside vtk.js depending on a slider position. We do have some example where we do similar thing with ArcticViewer.

https://github.com/Kitware/arctic-viewer/blob/master/scripts/examples/paraview/samples/VTKGeometry-can.py

Seb

**Comment by rmilne** [comment]
Thank you for the explanation and alternative strategies.  
All the best,
Russ
