### ISSUE TITLE
Strange DICOM rendering artifacts

### ISSUE THREAD

**Issue by AndreFrelicot** [Kitware/vtk-js#564]
Hello,
I need to load dicom files  but I'm getting strange results when rendering. Image is flipped and the pixels does not match what I see on OsiriX (left).

I load the dicom through ITK then I convert them using ItkToVtkFilter and use vtkXMLImageDataWriter to generate a XML VTI file.

See below the image comparisons and sample VTI file.

Do you have an idea what's happening ?

thank you

![bug_01](https://user-images.githubusercontent.com/2123744/35909545-41254506-0bf4-11e8-8f13-8fd86708fff1.png)
![bug_02](https://user-images.githubusercontent.com/2123744/35909546-41514aa2-0bf4-11e8-8ab2-b74e3e9668ec.png)
![bug_03](https://user-images.githubusercontent.com/2123744/35909548-417baf2c-0bf4-11e8-9106-e15f163600ab.png)
[output.vti.zip](https://github.com/Kitware/vtk-js/files/1702499/output.vti.zip)

**Comment by jourdain** [comment]
The orientation issue is expected as the vti format does not capture or keep the direction information of the scan. While vtk.js is able to render the data accordingly to that direction information.

@thewtex can explain how to keep that information along.

Regarding the pixel color, I tried to load your dataset in [ParaViewGlance](https://kitware.github.io/pv-web-viewer/) which use vtk.js and, it seems to me that the rendering is correct (except the orientation).

<img width="863" alt="screen shot 2018-02-07 at 7 47 38 am" src="https://user-images.githubusercontent.com/294518/35922780-af69783e-0bdb-11e8-8f66-647db8e09691.png">

**Comment by thewtex** [comment]
Hello @AndreFrelicot ,

While ITK reads in the DICOM image orientation, this information is lost in `itk::ImageToVTKImageFilter` because VTK does not support oriented images.

However, `vtk.js` does support oriented images :-). You can try loading your images with the [itk-vtk-image-viewer](https://kitware.github.io/itk-vtk-image-viewer/app/). This supports DICOM image files series and multi-frame DICOM images via [itk.js](https://github.com/InsightSoftwareConsortium/itk-js). The orientation information is passed from itk.js to vtk.js. One outstanding issue, though, is the pixel buffer arrangement, [described here](https://github.com/Kitware/itk-vtk-image-viewer/issues/40).

In your conversion script, a pixel type was likely used with a dynamic range that is too small, and you are likely seeing wrap-around artifacts in the observed images.

CC: @floryst @aylward @agirault  @martinken
