### ISSUE TITLE
Is unstructured grid available?

### ISSUE THREAD

**Issue by BotellaA** [Kitware/vtk-js#672]
I just find out about this project and I am really interested by this JavaScript version of VTK.

I am mainly using unstructured grid and I cannot see the corresponding class in this project.
Are they available? If not, do you think you will do it at some point?

Thanks

**Comment by jourdain** [comment]
vtk.js like VTK can only render a vtkPolyData (for geometry). The only difference is that the C++ version has filters to convert an unstructured grid into a polydata for rendering. In order to achieve that inside vtk.js we would like to compile the C++ code that we have in VTK into WebAssembly to work along with the vtk.js infrastructure. This is still work in progress but that would also mean, that we could also envision some data processing (clip, contour, streamlines...) using the same path.

Hopefully in a month or two we should have some basic implementation of such pipeline involving the compiled C++ class along with the JavaScript rendering...

**Comment by jourdain** [comment]
@thewtex feel free to add anything regarding the progress on WASM...

**Comment by jourdain** [comment]
see https://github.com/Kitware/vtk-js/issues/206
