### ISSUE TITLE
Issue with vtkImageMapper and slicing.

### ISSUE THREAD

**Issue by DominionSoftware** [Kitware/vtk-js#892]
There seems to be a problem with getSliceAtPosition().

The slice returned is not the correct slice for the position. The problem seems to be caused by these lines in ImageMapper.buildBufferObjects()
 
var nSlice = model.renderable.getSlice();
    if (ijkMode !== model.renderable.getSlicingMode()) {
      // If not IJK slicing, get the IJK slice from the XYZ position/slice
      nSlice = model.renderable.getSliceAtPosition(nSlice);
    }

in the problem case, nSlice is a slice index not a position. We are not using IJK slicing, and nSlice 
is the (Kth, I believe) slice rather than a position.

The app is only using X, Y, Z slicing mode.

This problem can be reproduced using my test code
https://github.com/DominionSoftware/Slicing

and setting the Scan Direction File to LR.json  and the View Direction to Sagittal.

Scrolling through the slices with the mouse wheel fails to go all the way through the image.
We report that we are at slice 44, but we are somewhere less than that.

**Comment by agirault** [comment]
> in the problem case, nSlice is a slice index not a position. We are not using IJK slicing, and nSlice
is the (Kth, I believe) slice rather than a position.

Just to confirm, are you saying "nSlice is currently a slice index but should not be" because you want to do XYZ slicing, or that "nSlice is a slice index in my app but should be a world position/depth"?

> The app is only using X, Y, Z slicing mode [...] and setting the Scan Direction File to LR.json and the View Direction to Sagittal.

I'll go with the assumption that you want to slice along a coordinate system different than the dataset (so not IJK, but XYZ). First of all, can you confirm you called [`ImageMapper.setSlicingMode`](https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L215) with `SlicingMode.X`, `SlicingMode.Y` or `SlicingMode.Z`  (or [`setXSlice`](https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L93), [`setYSlice`](https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L98), [`setZSlice`](https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L103) which internally set the slicing mode)?

An important limitation to note is that multi-planar reconstruction (MPR) is not yet available in vtk.js (as far as I know, unless recent changes). However, as discussed [here](https://github.com/Kitware/vtk-js/issues/499#issuecomment-368132722):
> We did some recent improvements to the ImageMapper to support flips and permutations in the direction matrix when slicing along X, Y, Z, which means it will slice correctly when either I, J or K are aligned with your slicing axis.

It should also support left handed systems thanks to @pieper and @martinken : https://github.com/Kitware/vtk-js/issues/858

What is the orientation matrix of your dataset? If it doesn't fall under one of the category listed above, you will require MPR support to properly render a reconstructed slice along X, Y, Z, or even any arbitrary axis not aligned with IJK. If that's the case, you should be seeing this warning:
https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L203-L209

If that's not the case and your data system coordinate is "aligned" with XYZ, we need to look at what could go wrong in `getSliceAtPosition`, but let us know first if any of that information is enough to help you.

**Comment by DominionSoftware** [comment]
I can confirm that I call setSlicingMode() on the mapper to X, Y, Z depending on the slice I want. I pass in a position that I pre-calculate from the Image Position Patient and the spacing.

It is working well except for the one case (well, 3 cases, but they are all the same).

In this code:

https://github.com/Kitware/vtk-js/blob/0f8a1970ebb89198757f034ed6754588a6637dde/Sources/Rendering/OpenGL/ImageMapper/index.js#L488

At this point, nSlice is a slice index, and as the comment says
// If not IJK slicing, get the IJK slice from the XYZ position/slice

and it's calling 

nSlice = model.renderable.getSliceAtPosition(nSlice);

with a slice number instead of a position.

My images have direction cosines that are aligned with IJK so I don't get any warning about inaccurate slicing.

**Comment by DominionSoftware** [comment]
It seems that if I comment out these lines
https://github.com/Kitware/vtk-js/blob/0f8a1970ebb89198757f034ed6754588a6637dde/Sources/Rendering/OpenGL/ImageMapper/index.js#L489
// don't do this
 //if (ijkMode !== model.renderable.getSlicingMode()) {
 //     // If not IJK slicing, get the IJK slice from the XYZ position/slice
  //    nSlice = model.renderable.getSliceAtPosition(nSlice);
  //  }

my code works as I expect. I get the correct slices. I think the lines above are suspicious: The mapper doesn't store the positions (i.e. in mm ) but as far as I can tell stores indexes. So, the mapper itself doesn't need to call getSliceAtPosition() unless it has a position in the spacing units of the image....

**Comment by agirault** [comment]
The terminology is indeed confusing because we made a workaround to basically do IJK slicing under the hood even when doing XYZ slicing, when possible. Because of this, `vtkImageMapper.slice` can be a slice index (if IJK) or a slice position in mm (if XYZ). For the later, it is necessary to go from mm to index by using  `vtkImageMapper. getSliceAtPosition`. The issue then becomes, why are you doing XYZ slicing, but nSlice (aka `vtkImageMapper.slice`) is index-based instead of mm?

If you do XYZ slicing, the slice number doesn't mean anything (if you want to slice by slice number, just do IJK), you should be using mm instead. The `vtkSliceRepresentationProxy` class shows (used by paraview-glance) shows how to then properly define the bounds the slice variable:
https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Proxy/Representations/SliceRepresentationProxy/index.js#L31-L52

While IJK uses the extent (index-based) and a step of 1 to hop from a slice to the next, XYZ requires to  use a slice value based on the bounds and a step based on the spacing (world coordinates).

Could you let us know if you are doing this already? If you are, then we need to understand why `nSlice` is an index, while it should be a world position.

**Comment by DominionSoftware** [comment]
I can confirm that I am only using mm positions. This is what I am used to doing in the image registration application I wrote using David Gobbis C++ code. Although I have to convert the world coordinates to positive positions. I move through the slices by adding spacing in mm for the next slice. As I mentioned I have a fairly complete test application that use the itkTestCases ( 3 of the six scan directions) of the Aorta Phantom scanned at GE years ago by Bill Lorenson

**Comment by DominionSoftware** [comment]
Actually, I am computing the index, there doesn't seem to be a setSliceAtPosition() call.

So what I do is: I compute a new position in mm and request the slice index for that position.
I wish to use mm in my code, in preparation for actual re-slicing to be available that's off an integer index....

I have the world positions as well but those are for reference.

So I do pass in an index. Sorry for the confusing. I don't see a way to set a slice position from a world position, only to get a slice index from a relative position. (perhaps the world position would work if the image origin is set to the world position?)



 const renderer = model.interactor.getCurrentRenderer();
            renderer.getActiveCamera().setParallelProjection(true);

            let mode = slice.getMapper().getSlicingMode();
            let currentPosition;
            let newPos;
            let worldPos;
            switch (mode) {
                case vtkImageMapper.SlicingMode.Z:
                    currentPosition = props.currentZIndex * props.zSpacing;
                    newPos = currentPosition + (props.zSpacing * increment);
                    worldPos = props.zPositions[props.currentZIndex];
                    break;
                case vtkImageMapper.SlicingMode.Y:
                    currentPosition = props.currentYIndex * props.ySpacing;
                    newPos = currentPosition + (props.ySpacing * increment);
                    worldPos = props.yPositions[props.currentYIndex];
                    break;
                case vtkImageMapper.SlicingMode.X:
                    currentPosition = props.currentXIndex * props.xSpacing;
                    newPos = currentPosition + (props.xSpacing * increment);
                    worldPos = props.xPositions[props.currentXIndex];
                    break;
            }

            if (newPos < 0) {
                newPos = 0.0;
            }
            slice.getMapper().setSlicingMode(mode);
            slice.getMapper().getSliceAtPosition(newPos);


            switch (mode) {
                case vtkImageMapper.SlicingMode.Z:
                    props.currentZIndex = idx;
                    slice.getMapper().setZSlice(idx);
                    break;
                case vtkImageMapper.SlicingMode.Y:
                    props.currentYIndex = idx;
                    slice.getMapper().setYSlice(idx + 1);
                    break;
                case vtkImageMapper.SlicingMode.X:
                    props.currentXIndex = idx;
                    slice.getMapper().setXSlice(idx);
                    break;
            }

            if (publicAPI.getLastCameraPosition() != undefined) {
                let pos = publicAPI.getLastCameraPosition();
                renderer.getActiveCamera().setPosition(pos[0], pos[1], pos[2]);
            } else {
                renderer.resetCamera();
            }

**Comment by DominionSoftware** [comment]
OK so, I think I see the confusion. When XYZ slicing I **should** pass a position in MM? Can you verify that? Thanks, that may fix the problem, it seems.

**Comment by agirault** [comment]
> When XYZ slicing I should pass a position in MM? 

Correct. mm along the slicing axis in the world coordinate system:

> If you do XYZ slicing, the slice number doesn't mean anything (if you want to slice by slice number, just do IJK), you should be using mm instead.

**Comment by DominionSoftware** [comment]
Thanks. I think adding a comment saying pass a position in image spacing coordinates (e.g mm) would be sufficient.

**Comment by agirault** [comment]
👍 
> I think adding a comment saying pass a position in image spacing coordinates (e.g mm) would be sufficient.

Where? Feel free to contribute where you think that would make sense. That would be true for XYZ only obviously.

**Comment by alfredomp** [comment]
@agirault @jourdain are there any initiatives to implement XYZ slicing? Just wanted to ask as this issues is almost 3 years old.

**Comment by jourdain** [comment]
People have been using the ResliceCursor as a workaround for now.
