### ISSUE TITLE
CT file rendering not aligned with axis

### ISSUE THREAD

**Issue by yh3ds** [Kitware/vtk-js#999]
Hello,
when I load a CT, the rendering is not aligned with the axis (see screen capture to illustrate).
The behavior is the same with my code running vtk.js, the demo website of Glance and Slicer.
But the rendering is well aligned with the axis if I load the same CT in ItkSnap.

Is there something specific to do ?
Is it a bug ?

Thank you very much for your help
![captureloadctnotalignedtoaxis](https://user-images.githubusercontent.com/43130636/52401595-559ec000-2ac2-11e9-878a-86843b35b1f6.PNG)

**Comment by agirault** [comment]
Two things I can think of here:

* vtk.js (and therefore Glance) do not fully-support arbitrary image orientation (see #499) **yet** (I believe some folks might be currently working on that?). If your dataset has a non-orthogonal orientation, you should see a warning in your browser console:
https://github.com/Kitware/vtk-js/blob/813f2f1/Sources/Rendering/Core/ImageMapper/index.js#L204-L208

* However, I believe the lack of slice reformatting described above - necessary for multi-planar reconstruction - would not cause the image to look tilted like this, but instead would make the slice "slide" in a direction along the plane of the screen when slicing through the dataset (or maybe both?). Also, you are mentioning that `3D Slicer` is showing the same results, and `3D Slicer` is our ground-truth for MPR viewing with proper orientation handling. Could it be that ITKSnap not handle MPR reconstruction? @jcfr @dzenanz

**Comment by dzenanz** [comment]
ITK-SNAP ignores orientation, and aligns the image axes with viewer axes. The same can be accomplished in 3D Slicer by "rotate to volume plane" button as discussed [here](https://discourse.slicer.org/t/rotate-to-volume-plane-flips-image-orientation-as-seen-in-the-slice-viewer/3648).

**Comment by agirault** [comment]
Thank you @dzenanz.

Therefore @yh3ds, both points I listed above probably apply to your use case: vtk.js is attempting to adjust the orientation of the image like 3DSlicer does (unlike ITK-SNAP) so the tilt is not a bug. However, given the tilt, we can infer that the orientation is not axis-aligned, so you will get the warning regarding the non-orthonormal transformation that can't currently be achieved without #499. 

If you are interested in getting the same result than ITK-SNAP (or slicer in "volume plane" mode), you can set your `ImageMapper`to slice along `IJK` instead of `XYZ`:
https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/Constants.js
Example: https://kitware.github.io/vtk-js/examples/MultiSliceImageMapper.html

Hth

**Comment by yh3ds** [comment]
Thank you for your help @agirault and the other in this thread

Your comment describes indeed what is happening : " However, I believe the lack of slice reformatting described above - necessary for multi-planar reconstruction - would not cause the image to look tilted like this, but instead would make the slice "slide" in a direction along the plane of the screen when slicing through the dataset"

Following your last post, the screen capture I sent was already sliced along I / J / K (I thought it will solve my problem)

If I look at the header of my nrrd file, I got :
space directions: (0.56412065029144287,4.2128463693690559e-020,-1.2055888594261299e-018) (4.212846464588871e-020,0.56274463018145382,0.039377522613529503) (4.2742158267082277e-018,-0.13960648725980887,1.995117972354773)

Do you have any more clue ?
Should I place the camera position and direction myself to avoid the problem ?

Thanks a lot
Yves

**Comment by agirault** [comment]
The "sliding" effect should not occur if you are slicing along IJK. Make sure you update the slice values with `set${I/J/K}Slice` or with `setSlicingMode(${I/J/K})` and `setSlice`: if you use `set${X/Y/Z}Slice` it will set the slicing mode to X/Y/Z.

There are then two different things using the orientation:
* **The slicing direction on the `ImageMapper` if doing XYZ slicing.** You will ignore the orientation if you use IJK slicing, so I think you are good on that front.
* **The model transform, to place/orient it properly in the world, which would cause the tilt.** To avoid that, you could override the transform (read from your nrrd file header) by the identity matrix with [`ImageData.setDirection`](https://github.com/Kitware/vtk-js/blob/8e47a7f/Sources/Common/DataModel/ImageData/index.js#L262-L269). I believe that should be enough, if not, try manually calling [`ImageData.computeTransforms`](https://github.com/Kitware/vtk-js/blob/8e47a7f/Sources/Common/DataModel/ImageData/index.js#L232) afterwards.

Other (more wanky solutions that above, depending on your needs) would be to:
- modify your nrrd file to have the space directions set to the identity matrix
- use the direction matrix to orient the camera to be orthogonal to the dataset IJK axis

**Comment by agirault** [comment]
> Setting the direction of the image data to identity improve greatly the rendering.

What do you mean by "improve greatly"? Does it get rid of the tilt? Maybe you can share more screenshots

> With the same model, I got a slight shift on I and K directions but not in J one

What do you mean by "shift"? The image is at an angle (tilted) or does it shift on the screen plane when scrolling through the slices? Maybe you can share more of your code, and a gif of what you are seeing?

> So I guess the remaining possibility is using the direction matrix to orient the camera ?

You have already set the direction matrix to the identity on the `ImageData`, so there is no need to re-orient the camera using a direction matrix, but make sure it is properly aligned on the IJK axis (which are now equal to the world XYZ axis since you use the identity as the orientation matrix):
```js
const camera = renderer.getActiveCamera();
const position = camera.getFocalPoint();
// offset along the slicing axis
const normal = mapper.getSlicingModeNormal();
position[0] += normal[0];
position[1] += normal[1];
position[2] += normal[2];
camera.setPosition(...position);
switch (mapper.getSlicingMode()) {
  case SlicingMode.I:
    camera.setViewUp([0, 1, 0]);
    break;
  case SlicingMode.J:
    camera.setViewUp([1, 0, 0]);
    break;
  case SlicingMode.K:
    camera.setViewUp([0, 1, 0]);
    break;
  default:
}
camera.setParallelProjection(true);
renderer.resetCamera();
```
Inspired from: https://kitware.github.io/vtk-js/examples/ImageMapper.html
With `ImageMapper.getSlicingModeNormal` defined here for IJK: https://github.com/Kitware/vtk-js/blob/40ab5c442600390c1c145c967c9fea2b9fd3c7c0/Sources/Rendering/Core/ImageMapper/index.js#L123-L140

**Comment by agirault** [comment]
> But aligning the camera to IJK like you suggest with your piece of code solve nearly completely the problem...

Great!

> for some images with sliceI for example sometimes I need [0,1,0] and sometimes [0,-1,0] to get the good orientation of image (for example on an head, nose looking toward left side)

If you actually wanted the image to be "properly" orientated (nose looking one way or another), you'd want to do the contrary of all this and actually use the direction matrix of the dataset for orientation and slicing.

If you want to find the proper values for the camera while doing IJK slicing, I fear this is going to be up to you experimenting with different view up and camera position values now: you could try opening your dataset in 3D Slicer, set it to `rotate to volume plane` as described by @dzenanz above, and figure out the camera pose to get the results you are looking for.
